### ISSUE TITLE
Data not being returned from targetProduction

### ISSUE THREAD

**Issue by nloadholtes** [chrislusf/teeproxy#11]
I noticed that I was never getting back the data or headers I was expecting from my "targetProduction" (aka the "-a" server).

Digging in I found that while the -a machine was returning a 200 (and all of the expected data) teeproxy was also see an error message. Because of that error message it would discard the data and just return the default 200 OK message.

(For the curious, the error message was: "Failed to receive from localhost:9090: persistent connection closed")

In Pull Request #10 I added in a check for the targetProduction side.

**Comment by chrislusf** [comment]
Somehow I did not see this issue until today. Sorry for that.

Maybe just need to improve the PR a bit.

**Comment by nloadholtes** [comment]
No prob, the comments on the PR were good points. I'm learning golang so there's no rush from my point of view on this PR.

**Comment by nloadholtes** [comment]
I thought I would have more time to work on this, but it looks like I don't.

I'm going to close this PR for now and revisit in the future.
