### ISSUE TITLE
Failed to receive from 192.168.2.7:4141: persistent connection closed

### ISSUE THREAD

**Issue by gexyitalia** [chrislusf/teeproxy#21]
Meanwhile, thank you very much, the tool is perfect and simple.
 My situation is this:

I have the first server (http1 - 192.168.2.7:4141) where there apache listening on port 4141, listening teeproxy on 80 and sends the first (192.168.2.7 and second (HTTP2). In both apache log (access_log) appear the same demands, so all ok, perfect.

But almost every request, stdout of the first server, the message
Failed to receive from 192.168.2.7:4141: persistent connection closed
What does it mean?

Thank you very much

**Comment by chrislusf** [comment]
seems fixed by https://github.com/chrislusf/teeproxy/pull/20 ?
