### ISSUE TITLE
Multiple teeproxies on same host

### ISSUE THREAD

**Issue by ratoji** [chrislusf/teeproxy#23]
Hello,

On a production server we have several web servers running on the same host, under distinct ports (8080, 8081, 8082). We want to have `teeproxy` forwarding to each of these ports, but we have no luck on doing this.

If running a single `teeproxy` process (eg.: using 8080 as A), everything works as expected.

Although, if launching a second or more `teeproxy` processes, nothing else is forwarded to the A server.

For example:

`teeproxy -l :9000 -a localhost:8080 -b another:7777`
`teeproxy -l :9001 -a localhost:8081 -b another:7777`

If kept the first line, A and B servers receive the requests. When launching the second process, A:8080 stops receiving requests, but B:7777 keeps receiving them (when posting to :9000).

Is this the expected behavior?

**Comment by chrislusf** [comment]
no. I do not even think its possible. Could you please do some debugging? the code should be easy to read and debug.

**Comment by ratoji** [comment]
Due to some deadline constraints I ended up using an nginx to have this behavior implemented (with a single teeproxy). It worked flawlessly. Thanks!
