### ISSUE TITLE
Updating deprecated library calls

### ISSUE THREAD

**Issue by girone** [chrislusf/teeproxy#25]
I replaced some meanwhile deprecated library methods with more recent code. Before creating a merge request I'd like to know which Go version I should aim for. Go 1.8 is out since February, but probably not many environments have it yet. Do you have any preferences?

Also I had to implement some new features to make it applicable for my scenario. For instance, optional setting of XFF headers, closing of connections or response error handling. I'd like to make these available, too.

**Comment by chrislusf** [comment]
I prefer to always build with latest Go version.
