### ISSUE TITLE
Ran teeproxy in front of varnish etc.

### ISSUE THREAD

**Issue by unisqu** [chrislusf/teeproxy#26]
I ran teeproxy in front of varnish etc. but I can't seem to get the actual IP or the x-forwarded-for IPs.
can you please guide me on how I can forward the actual IPs to varnish / haproxy / nginx? I'm forwarding the request but the IP will show it comes from the server instead of from the client.

**Comment by girone** [comment]
Teeproxy, in its current implementation, appends it's production backend's IP neither to the  "X-Forwarded-For" nor to the "Forwarded" header. You need to do this manually. I have a working implementation at hand, but it is not in shape to be released. Maybe I can do this in the next days. If you need it faster, PM me.

**Comment by unisqu** [comment]
i have no idea what you mean by doing it manually. but i do need it as soon as possible. it's a great little thing. I really hope that maybe it can do more than just 1 shadow traffic duplication. e.g. 1 to 3 clone. but it's still nice as long as the source ip is able to be viewed by varnish / haproxy / nginx through XFF or proxy protocol. please help. thanks.

**Comment by girone** [comment]
In order to reveal the IP of it's backend (what you pass to teeproxy as `-a`), the proxy needs to add this IP to the [XFF header](https://en.wikipedia.org/wiki/X-Forwarded-For) or the new standardized [Forwarded header](https://tools.ietf.org/html/rfc7239). The current version of teeproxy does not do this.

I am in the process of preparing my changes for a pull request, you might get them this afternoon (or whatever time it is at you place).

**Comment by girone** [comment]
Try this feature branch: https://github.com/ADITION/teeproxy/tree/feature/XFF-header

Start teeproxy as usual and then try the new command line flag `-forward-client-ip`. Does this what you were missing?

**Comment by unisqu** [comment]
i tried git clone https://github.com/ADITION/teeproxy.git
but
./teeproxy -l :8888 -a localhost:9000 -b localhost:9001 -forward-client-ip
gets
flag provided but not defined: -forward-client-ip

can u check?

**Comment by girone** [comment]
The new feature is not yet merged into the master branch. You need to `git
checkout feature/XFF` and `go build .`

Then the option should be available.

Best regards,
Jonas

2017-10-11 16:19 GMT+02:00 unisqu <notifications@github.com>:

**Comment by unisqu** [comment]
works perfectly. very well done.
can it do shadow traffic for multiple backends? (3 backends instead of 2) that'll make this perfect

**Comment by unisqu** [comment]
I discovered a major problem. the traffic connection drops when it's a POST method used. GET method works as normal but POST... doesnt work 100% of the time. i think the timeout factor needs to set higher. if so, how do i set the timeout for the return value?

**Comment by girone** [comment]
I haven't tested it with POST yet. If you think the timeout plays a role,
you can set it using the parameters. If that does not help, have an look
into the logfile /var/log/teeproxy.log

Am 12.10.2017 1:52 vorm. schrieb "unisqu" <notifications@github.com>:

**Comment by girone** [comment]
I am glad it helps you, too!

I don't want to change the behavior to have 1-to-3 output, because IMO it
deviates too much from the original behavior of teeproxy and from what the
command line tool `tee` does. However, as with `tee` you can solve your
problem by running multiple instances of teeproxy like this:

```
teeproxy -l 8081 -a <target1> -b <target2>
teeproxy -l 8080 -a <target3> -b localhost:8081  # the latter is the other
teeproxy instance
```

Am 12.10.2017 12:58 vorm. schrieb "unisqu" <notifications@github.com>:

**Comment by girone** [comment]
About the unexpected XFF content: How is your test scenario? 

Regarding the teeproxy functionality, it will always append the client IP (172.17.0.12 in your case) to the end of the header as shown by the unittests. This means that either the XFF header your setup inputs to teeproxy is different from what you report or your backend changes the headers afterwards. 

You can easily add some debugging output to the Go code to see the which headers go in and out of teeproxy to verify this. If you find a real problem within the code, please send me a unittest which reconstructs this and I will provide a fix.

BTW: Please do not completely rewrite your comments when making edits. This makes it really hard to give correct answers via the mailing list. If there is a new problem write a new post, please.

**Comment by unisqu** [comment]
is there an option to provide teeproxy with a debug mode to output in daemon mode real time?
i would like to resolve the issue below and teeproxy is perfect
-----
there's only 1 small problem with this X-Forwarded-For
If XFF = 144.76.N.N, 162.158.N.N
it will show 144.76.N.N, 172.17.0.12
can you make it XFF = 144.76.N.N, 162.158.N.N, 172.17.0.12 instead?
----

i havent tested on ssl but i'm very satisfied with the performance thus far. it's holding up very well.

**Comment by chrislusf** [comment]
@unisqu if no updates, please close this.
