### ISSUE TITLE
Can't seem to teeproxy some website extensions. e.g. .my

### ISSUE THREAD

**Issue by unisqu** [chrislusf/teeproxy#28]
i tried to teeproxy some websites with .my extension and it just doesnt work. not sure if it's the extension problem or otherwise. how do I check?

tee proxy also crashed with high load without any apparent warnings.
where is the log output? i've tried -debug but there's nothing shown. appreciate this help.

update : for the .my extension, i think was backend server side issue

**Comment by chrislusf** [comment]
no
