### ISSUE TITLE
Having this problem after prolonged use.

### ISSUE THREAD

**Issue by unisqu** [chrislusf/teeproxy#29]
2017/10/15 01:00:55 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s

How can I resolve this? How do I get too many open files? i've set ulimit -n 524288

Handling > 1 mil test traffic

**Comment by girone** [comment]
This is probably related to teeproxy not closing open connections or reusing them. Setting `ulimit` to a different value will only increase the time until you get the problem again. A temporary fix is to restart teeproxy automatically before you run out of connections. 

I experienced this problem, too, and developed a fix. Yet again, I need to refactor the changeset in a clean way but cannot do it before Wednesday, as we are at the end of the sprint and I need to work on a different topic. Will come back to it on Thursday.

**Comment by unisqu** [comment]
Thanks for the prompt reply. If this can be fixed, it will be perfect and wonderful. Thanks a lot of the hard work on this. I don't intend to increase the ulimit at this stage as I know it's only a temp fix. Will wait for your fix. Thanks a lot.

**Comment by unisqu** [comment]
Waiting for this whole day. Hoping to see the fix. Thanks in advance.

**Comment by unisqu** [comment]
Hi any feedback?

**Comment by girone** [comment]
I have a preview of the changes in the branch [feature/close-connections](https://github.com/ADITION/teeproxy/tree/feature/close-connections). It adds a parameter `-close-connections` with which you can force teeproxy to close the connections to the clients as well as those to the production and alternative targets. Furthermore, it fixes a bug in teeproxy where every successful request to the alternative target will leave a connection open.

Please update your clone to this branch, rebuild teeproxy and run it with the new parameter. I am curious about your feedback.

If your feedback is positive, I will include it into the upcoming pull requests.

**Comment by unisqu** [comment]
can you pls make forward-client-ip work too before i implement it? I need this forward-client-ip to work with my existing system

**Comment by girone** [comment]
The branch is based upon the previous changes as you can confirm here:
https://github.com/ADITION/teeproxy/network



2017-10-23 12:09 GMT+02:00 unisqu <notifications@github.com>:

**Comment by unisqu** [comment]
Ok. i got it. I'm having one last problem with teeproxy
it's the X-Forwarded-For.
It drops the pending value e.g.
XFF IP = ABC, BCD, EFG
generated XFF IP = ABC, INTERNAL IP OF TEEPROXY, INTERNAL IP OF TEEPROXY

can this be resolved? i'm just running the process now. it seems there is some issue with restarting the instance... i will test more and hope it runs for 3 days

**Comment by girone** [comment]
This sounds like nothing related to teeproxy but to your local test setup. You can verify this by adding `Logger.Printf("target: %s, header: %s", request.URL, request.Header.Get(XFF_HEADER))` _before_ [line 87](https://github.com/ADITION/teeproxy/blob/feature/close-connections/teeproxy.go#L87). Build teeproxy again and then check the log output when the behavior (the X-Forwarded-For value) changes. Does the output in the log change, too?

If it does, please describe your setup in more detail. If not, there is some magic going on in your environment, which is hard to debug from remote.

**Comment by chrislusf** [comment]
@unisqu if no updates, please close this.
