### ISSUE TITLE
teeproxy response headers issue

### ISSUE THREAD

**Issue by threedliteguy** [chrislusf/teeproxy#3]
It appears the response headers are being a bit mangled.  For example, the content-type changes to text/plain instead of application/json, and the HTTP/1.1 line appears in the http response body.
I am using teeproxy in front of a json rest web service hitting with chrome using Advanced REST Client chrome plugin. Hitting the web service directly works.

**Comment by chrislusf** [comment]
Can you please help to debug this? It's just 140 lines of code.

**Comment by chrislusf** [comment]
fixed.
