### ISSUE TITLE
If fronted by Cloudflare, XFF shows CloudFlare IP.

### ISSUE THREAD

**Issue by unisqu** [chrislusf/teeproxy#30]
1. If fronted by Cloudflare, XFF shows CloudFlare IP

I'm doing load testing currently but I really need the IP to reflect real IPs.
e.g. XFF = Client IP, Cloudflare IP etc

2. I also realised something with teeproxy, I'm not sure how to "DROP" the connection when an IP is detected. How do I drop the connection instead of the connection always returning some value? (even if blank html)

**Comment by chrislusf** [comment]
@unisqu if no updates, please close this.
