### ISSUE TITLE
Please help on one issue

### ISSUE THREAD

**Issue by unisqu** [chrislusf/teeproxy#32]
I would like to hard code 1 IP to drop the connection and not make it return any values. I realised you have 
                defer resp.Body.Close()
in the code. Can you teach me where to slot in the code for the 1 IP to drop the connection?

more like for a firewall application, i will make it detect an IP and drop the connection instead of returning an empty 0 byte "html" request. pls help on this. i'm new to golang.

Please show me the lines inside this function
func (h handler) ServeHTTP(w http.ResponseWriter, req *http.Request) {

//e.g. ip = '123.123.123.123'
if ( ip == "123.123.123.123" ) {
     drop connection (without opening more files of affecting connections etc)
}

**Comment by unisqu** [comment]
I've tested running the system but somehow the port / resource contention of this program is a bit high... i need to use the ip drop part to test in full. please help. thanks.

**Comment by unisqu** [comment]
i added the following code and it works... along these lines
if(ip == "123...123"){
    tr := &http.Transport{}
    tr.CancelRequest(req)
}

but the load jumps 50% more. which is very high.is this the correct way to do it?

**Comment by unisqu** [comment]
i've tried dos teeproxy, but it still returns 404 though. can it not return anything?

**Comment by chrislusf** [comment]
@unisqu if no updates, please close this.
