### ISSUE TITLE
One problem discovered in teeproxy after running for 2 days

### ISSUE THREAD

**Issue by unisqu** [chrislusf/teeproxy#33]
http: multiple response.WriteHeader calls

The above "error", not sure if it's critical but getting a lot of that.

Is there a fix for this?

**Comment by girone** [comment]
Can you turn on logging and post the requests which cause these errors?
Disk and RAM usage are still OK after running for that long?

Am 20.11.2017 1:21 nachm. schrieb "unisqu" <notifications@github.com>:

**Comment by unisqu** [comment]
ok i think it's a problem of mine. let me run it again for a week and get back to you again

**Comment by chrislusf** [comment]
@unisqu if no updates, please close this.
