### ISSUE TITLE
Is teeproxy keep-alive enabled?

### ISSUE THREAD

**Issue by unisqu** [chrislusf/teeproxy#34]
Is teeproxy keep-alive enabled? How do I make it keep-alive?

I've been testing it for quite some time, though I havent run it for a week, it seems to hold up ok for 3 days. I needed to reset from time to time (because of some other additional features I've added to it)

How do I do keep-alive again?

**Comment by unisqu** [comment]
Just realised it's this line... can I not make it false? If so, I will have the problems previously addressed right? Connection dropped etc... is it?
        if *closeConnections {
                // Close connections to clients by setting the "Connection": "close" header in the response.
                server.SetKeepAlivesEnabled(false)
        }

**Comment by unisqu** [comment]
From here : https://groups.google.com/forum/#!topic/golang-nuts/nTU1tHPo-iU
I saw these lines:

                response.Body.Close()
		response = nil
		transport.CloseIdleConnections()

Where should I input these? Can you help?

**Comment by girone** [comment]
I am assuming that you are still using the branch I provided you with:
https://github.com/ADITION/teeproxy/tree/feature/close-connections

As documented on the frontpage README.md, this version of teeproxy has an
option `-close-connections` which will tell teeproxy to terminate the
connections as soon as they become idle. The default is false, so if you do
not specify the parameter, the connections to the outside should be kept
open, if the remote end supports it.

2017-12-06 12:58 GMT+01:00 unisqu <notifications@github.com>:

**Comment by unisqu** [comment]
Yes, but I thought that was why the connection is dropping after it exceeds the limits of file opened, I've enabled it again but I realised there should be a mechanism to time out some of these open connections.

Can you help? those lines i found online should be helpful. Of course I would like to have keep alive open but to also not have too many files opened at the same time. I've checked consistently running the program with connection close set to false and it's opening a lot of files already. Can you help?

**Comment by girone** [comment]
It does not strike me as something you wish to do manually, it should
rather be done by configuration. In this line, the KeepAlive timeout is
set:
https://github.com/ADITION/teeproxy/blob/feature/close-connections/teeproxy.go#L71

Version >= 1.8 of go, there is also an `IdleConnTimeout` to
`http.Transport`, which could be helpful.

2017-12-06 13:35 GMT+01:00 unisqu <notifications@github.com>:

**Comment by chrislusf** [comment]
@unisqu if no updates, please close this.
