### ISSUE TITLE
Can you make teeproxy http2 compatible?

### ISSUE THREAD

**Issue by unisqu** [chrislusf/teeproxy#35]
I'm using it currently without any issues except I think it's not http2 compatible. How can I make that happen?

**Comment by girone** [comment]
According to [the docs](https://godoc.org/golang.org/x/net/http2) it should be compatible starting from Go 1.6. Since teeproxy uses the package `net/http`, it is indirectly used:

> This package is low-level and intended to be used directly by very few people. Most users will use it indirectly through the automatic use by the net/http package (from Go 1.6 and later). For use in earlier Go versions see ConfigureServer. (Transport support requires Go 1.6 or later)

Or do you have any evidence that it does is not compatible?

**Comment by unisqu** [comment]
I now know it's compatible. How do I enable it? Sorry for the late reply.
