### ISSUE TITLE
http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by jkrogma** [chrislusf/teeproxy#43]
Hi,

we are currently using teeproxy in a migration use case. Our complete tracking infrastructure is about to be migrated to an alternative hosting facility. Therefore we have to duplicate HTTP traffic for a limited time period.

We installed and activated teeproxy and it is working like a charm ... but ... our syslog is filled with warnings like this:
`2018/08/28 08:58:25 http: multiple response.WriteHeader calls`

Looking into the source, we were able to identify that the WriteHeader() method is indeed executed twice:
``` go
...
        resp := handleRequest(productionRequest, timeout)

        if resp != nil {
                defer resp.Body.Close()

                // Forward response headers.
                for k, v := range resp.Header {
                        w.Header()[k] = v
                }
                w.WriteHeader(resp.StatusCode)

                // Forward response body.
                body, _ := ioutil.ReadAll(resp.Body)
                w.Write(body)
        }
        w.WriteHeader(resp.StatusCode)
        io.Copy(w, resp.Body)
...
```

IMHO the second call is obsolete. The error messages do not inflict the functionality of teeproxy but they are definitely filling our logfiles. So we removed the line in question and rebuild teeproxy. It is still working without problems. The error messages have been gone.

**Comment by chrislusf** [comment]
thanks for reporting this!

Added the fix and also improved the code a bit.
