### ISSUE TITLE
[Feature request] Limit duplication to specific HTTP methods

### ISSUE THREAD

**Issue by kasisnu** [chrislusf/teeproxy#45]
Hello,

We have a use case where duplication of traffic is needed, but we only want to duplicate specific HTTP methods, ex. GETs.
One reason to do this is if both A and B use the same underlying datastores in which case multiple POSTs, etc are not idempotent, but GETs probably are.

I'm happy to volunteer a patch for this if there's interest.

**Comment by chrislusf** [comment]
good idea! Welcome the patch!
