### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by Arnold1** [chrislusf/teeproxy#51]
@chrislusf

hi, i have the following architecture with have http trafffic (POST request/response):
```
master_server ---- process_server 
                  (service: calcData)
```
here is how i would like to use teeproxy. would run on process_server read the incomming traffic from master_server and forward the traffic to:
- service: calcData running on process_server
- service: calcData running on qa_server
```
master_server ----- process_server ----- qa_server
                       teeproxy <----->  service: calcData
                          ^
                          |
                          v
                    service: calcData
```

       
i have a few questions:
- how much traffic can teeproxy handle? is it able to handle 60k QPS?
- i have traffic with low latency:
   the latency between master_server and process server is 1-20ms
   teeproxy would run on process_server and forward the traffic to qa_server
   is teeproxy able to handle such low latency?
- whats the overhead to include teeproxy for forwarding http traffic to qa_server?

**Comment by chrislusf** [comment]
perf depends on many things. better test it with real traffic.
