### ISSUE TITLE
Create Automated Build on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [chrislusf/teeproxy#53]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add a packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags automatically from git tags & branches.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags. Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.
Added to that, there are a handful of teeproxy public images in Docker Hub, some of them unmaintained for 4 years. Linking the 'official', straight from source build image on the readme would avoid people using an outdated version of the software by mistake,

Since there is already a Dockerfile in the repo, just a free Docker Hub account and a quick setup will do. Ping me if I can be of any help.

**Comment by pataquets** [comment]
@chrislusf ping

**Comment by chrislusf** [comment]
done! Thanks!

**Comment by pataquets** [comment]
Awesome, thanks!
