### ISSUE TITLE
What kind of load has this been used with?

### ISSUE THREAD

**Issue by erick-thompson** [chrislusf/teeproxy#8]
I found this via a StackOverflow post, and it looks like it is exactly what I need. I was able to get it working on Windows with no issues (go FTW). 

I was planning to put a server running this into my haproxy rotation, and I can limit the traffic, but I'm not sure what it can handle. My question is, has this been used under load? If so, how much? 

Thanks!
Erick

**Comment by chrislusf** [comment]
Seems a simple apache benchmark will do the load testing. It's better to use your use case to test it.
